// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_NOTIFICACIONES_NO_LEIDAS = 'SET_NOTIFICACIONES_NO_LEIDAS';
export const CLEAR_NOTIFICACIONES_NO_LEIDAS ='CLEAR_NOTIFICACIONES_NO_LEIDAS';
//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//dataReducer types
export const SET_PEDIDOS = 'SET_PEDIDOS';
export const CLEAR_PEDIDOS = 'CLEAR_PEDIDOS';
export const SET_PRODUCTOS = 'SET_PRODUCTOS';
export const CLEAR_PRODUCTOS = 'CLEAR_PRODUCTOS';
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const CLEAR_CATEGORIAS = 'CLEAR_CATEGORIAS';
export const SET_PERSONAL = 'SET_PERSONAL';
export const CLEAR_PERSONAL = 'CLEAR_PERSONAL';
export const SET_VEHICULOS = 'SET_VEHICULOS';
export const CLEAR_VEHICULOS = 'CLEAR_VEHICULOS';