// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_NOTIFICACIONES_NO_LEIDAS = 'SET_NOTIFICACIONES_NO_LEIDAS';
export const CLEAR_NOTIFICACIONES_NO_LEIDAS ='CLEAR_NOTIFICACIONES_NO_LEIDAS';
export const SET_NOTIFICACIONES_LEIDAS = 'SET_NOTIFICACIONES_LEIDAS';
//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//dataReducer types
export const SET_PEDIDOS = 'SET_PEDIDOS';
export const CLEAR_PEDIDOS = 'CLEAR_PEDIDOS';
export const SET_PRODUCTOS = 'SET_PRODUCTOS';
export const CLEAR_PRODUCTOS = 'CLEAR_PRODUCTOS';
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const CLEAR_CATEGORIAS = 'CLEAR_CATEGORIAS';
export const SET_PERSONAL = 'SET_PERSONAL';
export const CLEAR_PERSONAL = 'CLEAR_PERSONAL';
export const SET_VEHICULOS = 'SET_VEHICULOS';
export const CLEAR_VEHICULOS = 'CLEAR_VEHICULOS';
export const SET_CONTRATO = 'SET_CONTRATO';
export const CLEAR_CONTRATO = 'CLEAR_CONTRATO';
export const DELETE_PERSONAL = 'DELETE_PERSONAL';
export const SET_OCUPACION = 'SET_OCUPACION';
export const CLEAR_OCUPACION = 'CLEAR_OCUPACION';
export const SET_ISDEFAULTER = 'SET_ISDEFAULTER';
export const CLEAR_ISDEFAULTER = 'CLEAR_ISDEFAULTER';
export const SET_CLIENTE = 'SET_CLIENTE';
export const CLEAR_CLIENTE = 'CLEAR_CLIENTE';
export const CLEAR = 'CLEAR';
//ClienteReducer types
export const SET_CLIENTES = 'SET_CLIENTES';
export const CLEAR_CLIENTES = 'CLEAR_CLIENTES';
export const SET_FACTURAS = 'SET_FACTURAS';
export const CLEAR_FACTURAS = 'CLEAR_FACTURAS';