// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_NOTIFICACIONES_NO_LEIDAS = 'SET_NOTIFICACIONES_NO_LEIDAS';
export const CLEAR_NOTIFICACIONES_NO_LEIDAS ='CLEAR_NOTIFICACIONES_NO_LEIDAS';
export const SET_NOTIFICACIONES_LEIDAS = 'SET_NOTIFICACIONES_LEIDAS';
//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ENVIADO = 'SET_ENVIADO';
export const CLEAR_ENVIADO = 'CLEAR_ENVIADO';

//dataReducer types
export const SET_PEDIDOS = 'SET_PEDIDOS';
export const CLEAR_PEDIDOS = 'CLEAR_PEDIDOS';
export const SET_PEDIDO = 'SET_PEDIDO';
export const CLEAR_PEDIDO = 'CLEAR_PEDIDO';
export const SET_PRODUCTOS = 'SET_PRODUCTOS';
export const CLEAR_PRODUCTOS = 'CLEAR_PRODUCTOS';
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const CLEAR_CATEGORIAS = 'CLEAR_CATEGORIAS';
export const SET_PERSONAL = 'SET_PERSONAL';
export const CLEAR_PERSONAL = 'CLEAR_PERSONAL';
export const SET_VEHICULOS = 'SET_VEHICULOS';
export const CLEAR_VEHICULOS = 'CLEAR_VEHICULOS';
export const SET_CONTRATO = 'SET_CONTRATO';
export const CLEAR_CONTRATO = 'CLEAR_CONTRATO';
export const DELETE_PERSONAL = 'DELETE_PERSONAL';
export const SET_OCUPACION = 'SET_OCUPACION';
export const CLEAR_OCUPACION = 'CLEAR_OCUPACION';
export const SET_ISDEFAULTER = 'SET_ISDEFAULTER';
export const CLEAR_ISDEFAULTER = 'CLEAR_ISDEFAULTER';
export const SET_CLIENTE = 'SET_CLIENTE';
export const CLEAR_CLIENTE = 'CLEAR_CLIENTE';
export const CLEAR = 'CLEAR';
export const SET_VEHICULOSITVSEGUROREPARACION = 'SET_VEHICULOSITVSEGUROREPARACION';
export const CLEAR_VEHICULOSITVSEGUROREPARACION = 'CLEAR_VEHICULOSITVSEGUROREPARACION';
export const SET_ALMACEN = 'SET_ALMACEN';
export const CLEAR_ALMACEN = 'CLEAR_ALMACEN';
export const SET_POSTPEDIDO = 'SET_POSTPEDIDO';
export const SET_TIPOSVEHICULOS = 'SET_TIPOSVEHICULOS';
export const CLEAR_TIPOSVEHICULOS = 'CLEAR_TIPOSVEHICULOS';
export const SET_BALANCE = 'SET_BALANCE';
export const CLEAR_BALANCE = 'CLEAR_BALANCE';
export const SET_ALMACENGESTIONENCARGADO = 'SET_ALMACENGESTIONENCARGADO';
export const CLEAR_ALMACENGESTIONENCARGADO = 'CLEAR_ALMACENGESTIONENCARGADO';
export const SET_FACTURA = 'SET_FACTURA';

//ClienteReducer types
export const SET_CLIENTES = 'SET_CLIENTES';
export const CLEAR_CLIENTES = 'CLEAR_CLIENTES';
export const SET_FACTURAS = 'SET_FACTURAS';
export const CLEAR_FACTURAS = 'CLEAR_FACTURAS';
export const SET_ALMACENGESTION = 'SET_ALMACENGESTION';
export const CLEAR_ALMACENGESTION = 'CLEAR_ALMACENGESTION';

//productosReducer types
export const SET_PRODUCTOS_PAGINADO = 'SET_PRODUCTOS_PAGINADO';
export const CLEAR_PRODUCTOS_PAGINADO = 'CLEAR_PRODUCTOS_PAGINADO';
export const SET_CATEGORIASALM = 'SET_CATEGORIASALM';
export const CLEAR_CATEGORIASALM = 'CLEAR_CATEGORIASALM';

//proveedorReducer types
export const SET_PROVEEDORES = 'SET_PROVEEDORES';
export const CLEAR_PROVEEDORES = 'CLEAR_PROVEEDORES';